inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/webpack*'
    - 'bin/yarn'
    - 'bin/spring'
    - 'db/migrate/*'
    - 'db/schema.rb'

# Top-level class document is self-explanatory and therefore unnecessary.
Style/Documentation:
  Enabled: false

# Frozen string literals is default in Ruby 3.0
Style/FrozenStringLiteralComment:
  Enabled: false

# numeric literals without _ between groups of digits in them
Style/NumericLiterals:
  MinDigits: 6

# default is 120
Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

# Use the recommended enforced style
Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: link_or_button

#スタイルの中に、"場合"を追加して日本語に対応
RSpec/ContextWording:
   AllowedPatterns:
     - 場合$

#ユーザー編集機能では必要なので、member_spec.rbのみ
RSpec/MultipleMemoizedHelpers:
  Exclude:
  - 'spec/system/members_spec.rb'

# ToDo: MetricsのMax値調整
Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 150

Metrics/BlockLength:
  Max: 90
  Exclude:
    - 'config/environments/development.rb'

# ToDo: RSpecのMax値調整
RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 15